### ISSUE TITLE
Hello, may I ask which simulator you use the generate virtual images?

### ISSUE THREAD

**Issue by sheyehs** [leo94-hk/SelfTraining-6D#6]
Hello, I am a student from NYU. I appreciate your work because it has a very clear logic structure and a thorough experiment questions section. Is it bothering you that if I ask what simulator you used to generate the virtual datasets? I am newly in computer vision and wondering which simulator to choose. I know pybullet but it is mainly for physics dynamics and it visual effects are not good. I found your simulated images are perfect so I am curious about the tools you use. Thanks for your response.

**Comment by sheyehs** [comment]
Oh, sorry. I just found you possibly use Blender. Is that right?

**Comment by ck-kai** [comment]
Hi, thanks for your interest in our work. Yes, exactly. We use Blender to generate virtual images.

**Comment by sheyehs** [comment]
thx.
